version: 2

sources:
  - name: housing_raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BQ_DATASET_RAW', 'housing_raw') }}"
    tables:
      - name: raw_buildings
      - name: raw_rooms
      - name: raw_students
      - name: raw_assignments
